name: flutter_reduct
description: An elementary yet adaptable state management solution for Dart.
version: 1.0.1
repository: https://github.com/Eronildo/flutter_reduct

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduct: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
