name: flutter_reduct
description: Flutter widgets for reduct library.
version: 1.0.0
repository: https://github.com/Eronildo/flutter_reduct

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  reduct: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
